// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtMhL-vXbBt3EsVZZL7XeGSFOTsfGnDRs',
    appId: '1:947348071010:web:8c7ef1e45944069f5ba73b',
    messagingSenderId: '947348071010',
    projectId: 'qrcode-35068',
    authDomain: 'qrcode-35068.firebaseapp.com',
    storageBucket: 'qrcode-35068.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4F1LyYU1LGKL7v_MD59UOwK6GLO7tfo0',
    appId: '1:947348071010:android:3cde109b91d5a9c45ba73b',
    messagingSenderId: '947348071010',
    projectId: 'qrcode-35068',
    storageBucket: 'qrcode-35068.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdSfz4AZxWRiyzxym57bjELkoCoz3B6oU',
    appId: '1:947348071010:ios:d56627369d6c9e875ba73b',
    messagingSenderId: '947348071010',
    projectId: 'qrcode-35068',
    storageBucket: 'qrcode-35068.appspot.com',
    iosBundleId: 'com.example.qrcodeBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdSfz4AZxWRiyzxym57bjELkoCoz3B6oU',
    appId: '1:947348071010:ios:f9c02b6d36d0b08e5ba73b',
    messagingSenderId: '947348071010',
    projectId: 'qrcode-35068',
    storageBucket: 'qrcode-35068.appspot.com',
    iosBundleId: 'com.example.qrcodeBloc.RunnerTests',
  );
}
